
# name: build-and-lint

# # triggeres: define when this workflow should run
# # trigger on  push to these branches  
# on:
# push:
# branches: [main, dev]
# pull_request:
# branches: [main, dev]

# # define a multiple jobs also
# jobs:
# build-and-lint:
# runs-on: ubuntu-latest
# steps:
# - name: Checkout repo
# uses: actions/checkout@v3

# name: Setup Node
# uses: actions/setup-node@v3
# with:
# node-version: 20
# name: Install backend deps
# working-directory: server
# run: npm ci
# name: Lint backend
# working-directory: server
# run: npm run lint -- --max-warnings=0
# name: Install frontend deps
# working-directory: client
# run: npm ci
# name: Lint frontend
# working-directory: client
# 3
# run: npm run lint -- --max-warnings=0

# name: Build backend Docker image
# run: docker build -t backend ./server

# name: Build frontend Docker image
# run: docker build -t frontend ./client


name: build-and-lint

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # ---------------- BACKEND ----------------
      - name: Install backend dependencies
        working-directory: backend
        run: npm ci

      - name: Lint backend
        working-directory: backend
        run: npm run lint -- --max-warnings=0

      # ---------------- FRONTEND ----------------
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint -- --max-warnings=0

      # ---------------- DOCKER ----------------
      - name: Build backend Docker image
        run: docker build -t backend ./backend

      - name: Build frontend Docker image
        run: docker build -t frontend ./frontend